#!/usr/local/cpanel/3rdparty/bin/perl

use Cpanel::Version ();

if ( $Cpanel::Version::MAJORVERSION < 11.78 ) {
    print "This addon requires 11.78 or later.\n";
    exit(1);
}

mkdir( "/var/cpanel/addons", 0755 );
mkdir( "/var/cpanel/addons/maldet", 0700 );

system '/usr/bin/rsync', '-rlptD', 'src/bin', '/var/cpanel/addons/maldet/';

if (! -e '/usr/local/sbin/maldet') {
  if (-X "/var/cpanel/addons/maldet/bin/install_lmd") {
    system '/var/cpanel/addons/maldet/bin/install_lmd';
    if ($? != 0) {
      print "LMD Install Script Failed\n";
      exit(1);
    }
  } else {
      print "LMD Install Script Not Found?\n";
      exit(1);
  }
} else {
  print "LMD installed\n";
}

mkdir( "/usr/local/cpanel/whostmgr/docroot/cgi/addons", 0755 ) if !-e "/usr/local/cpanel/whostmgr/docroot/cgi/addons";
mkdir( "/usr/local/cpanel/base/frontend/paper_lantern/maldet", 0755 ) if !-e "/usr/local/cpanel/base/frontend/paper_lantern/maldet";
mkdir( "/usr/local/cpanel/whostmgr/docroot/cgi/addons/maldet", 0700 );
mkdir( "/var/cpanel/apps", 0755 );
mkdir( "/usr/local/cpanel/whostmgr/docroot/templates/maldet/", 0700 );

install( "-o", "root", "-g", "wheel", "-m" . "0700", "src/cgi/index.cgi", "/usr/local/cpanel/whostmgr/docroot/cgi/addons/maldet/index.cgi" );
install( "-o", "root", "-g", "wheel", "-m" . "0600", "version.txt", "/usr/local/cpanel/whostmgr/docroot/cgi/addons/maldet/version.txt" );
install( "-o", "root", "-g", "wheel", "-m" . "0755", "src/cron/daily", "/etc/cron.daily/cp-maldet" );

install( "-o", "root", "-g", "wheel", "-m" . "0400", "src/templates/maldet.tmpl", "/usr/local/cpanel/whostmgr/docroot/templates/maldet/index.tmpl" );
install( "-o", "root", "-g", "wheel", "-m" . "04600", "src/templates/update.tmpl", "/usr/local/cpanel/whostmgr/docroot/templates/maldet/update.tmpl" );
install( "-o", "root", "-g", "wheel", "-m" . "0400", "src/templates/err.tmpl", "/usr/local/cpanel/whostmgr/docroot/templates/maldet/err.tmpl" );
install( "-o", "root", "-g", "wheel", "-m" . "0400", "src/templates/report.tmpl", "/usr/local/cpanel/whostmgr/docroot/templates/maldet/report.tmpl" );
install( "-o", "root", "-g", "wheel", "-m" . "0400", "src/templates/editor.tmpl", "/usr/local/cpanel/whostmgr/docroot/templates/maldet/editor.tmpl" );
install( "-o", "root", "-g", "wheel", "-m" . "0400", "src/templates/start_scan.tmpl", "/usr/local/cpanel/whostmgr/docroot/templates/maldet/start_scan.tmpl" );

install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/lib/Maldet.pm", "/usr/local/cpanel/Cpanel/Plugins/Maldet.pm" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/lib/API/Maldet.pm", "/usr/local/cpanel/Cpanel/API/Maldet.pm" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/lib/WHM/Maldet.pm", "/usr/local/cpanel/Whostmgr/Maldet.pm" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/paper_lantern/maldet/index.html.tt", "/usr/local/cpanel/base/frontend/paper_lantern/maldet/index.html.tt" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/paper_lantern/maldet/report.html.tt", "/usr/local/cpanel/base/frontend/paper_lantern/maldet/report.html.tt" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/paper_lantern/maldet/scan.html.tt", "/usr/local/cpanel/base/frontend/paper_lantern/maldet/scan.html.tt" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/paper_lantern/maldet/latest.html.tt", "/usr/local/cpanel/base/frontend/paper_lantern/maldet/latest.html.tt" );
install( "-o", "root", "-g", "wheel", "-m" . "0444", "src/paper_lantern/maldet/action.html.tt", "/usr/local/cpanel/base/frontend/paper_lantern/maldet/action.html.tt" );


system "/usr/local/cpanel/bin/register_appconfig", "appconfig/maldet.conf";

mkdir( "/usr/local/cpanel/whostmgr/docroot/addon_plugins", 0755 ) if !-e "/usr/local/cpanel/whostmgr/docroot/addon_plugins";
install( "-o", "root", "-g", "wheel", "-m" . "0600", "icon/ico-maldet.png", "/usr/local/cpanel/whostmgr/docroot/addon_plugins/ico-maldet.png" );

print "cPanel Linux Malware Detect installed into WHM.\n";

system "/usr/local/cpanel/scripts/install_plugin", "appconfig/maldet.tar.gz";

exit(0);

sub install {
    system( "/usr/bin/install", @_ );
}
