#!/bin/bash
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH

dir=`mktemp -d` && cd $dir

trap "rm -rf $dir" EXIT

# sleep for random value to give upstream a bit of headroom
sleep $(echo $RANDOM | cut -c1-3) >> /dev/null 2>&1

/var/cpanel/addons/maldet/update

# if were running inotify monitoring, send daily hit summary
if [ "$(ps -A --user root -o "comm" | grep inotifywait)" ]; then
        /usr/local/maldetect/maldet --alert-daily >> /dev/null 2>&1
elif [ -d "/usr/local/cpanel" ] && [ -x "/var/cpanel/addons/maldet/bin/homematch" ]; then
        #cpanel
        HOMEMATCH=`/var/cpanel/addons/maldet/bin/homematch`
        /usr/local/maldetect/maldet -b -r $HOMEMATCH?/?/public_html 2 >> /dev/null 2>&1
fi
